##########################################
#                                        #
#       Tadukoo Bible Config             #
##########################################
# NEVER change this setting!
version: '1.0'

# Set this to whatever language you want to use. Using the name of the language instead of the actual language
# file's name will change it to that language file on start up.
language: en_US

# Set this to false if you want to disable the checks of this file during start up.
startup-checks: true

# These decide whether to keep track of statistics.
# player statistics is for statistics per player, while plugin statistics is for everyone on the server.
statistics: 
  player: true
  plugin: true

# This is the book, chapter, verse, and translation used for commands when none is specified.
# DefaultChapter, DefaultVerse, and DefaultPart must be a number in parentheses.
default:
  translation: KJV
  book: Genesis
  chapter: '1'
  verse: '1'
  part: '1'

# This decides whether to use permissions or not.
# Note: If you use a permissions plugin and set TadukooBible.use to false, 
# it will still disable use of the plugin even if this is false.
permissions: true

# This will disable getting the Bible as books if set to false.
# Note: You could always just get the book config for your translation from the site.
books: true

# This will show messages to help with finding errors in the plugin if set to true.
debug: false

##########################################
#                                        #
#              Translations              #
##########################################
# Enable or disable translations here.
#(Note: You must still have the files for that translation or it won't work.)
KJV: true
OEB: true
