name: Tadukoo Bible
main: com.gmail.lucario77777777.TBP.Main
version: Alpha 0.1.2
description: Read the Bible using commands.
commands:
   bible:
      description: Read the Bible.
      usage: /<command>
      permission: TadukooBible.use
      permission-message: You don't have <permission>.
permissions:
   TadukooBible.use:
      description: Gives access to the plugin.
      default: true
   TadukooBible.getbooks:
      description: Allows use of /bible getbook|book [book] [part #] [translation]
      default: true
