# 
#                                        #
#       Tadukoo Bible Config             #
DefaultTranslation: KJV
DefaultBook: Genesis
DefaultChapter: '1'
DefaultVerse: '1'
DefaultPart: '1'
Permissions: true
PlayerRecords: true
Books: true
KJV: true
