##########################################
#                                        #
#       Tadukoo Bible Config             #
##########################################
# This is the translation used for commands when none is specified.
DefaultTranslation: KJV

# This decides whether to use permissions or not.
# Note: If you use a permissions plugin and set TadukooBible.use to false, 
# it will still disable use of the plugin even if this is false.
Permissions: true

# Whether to keep records of last verse viewed, last book gotten, etc.
# *Required in order to use previous/next/last for anything.
PlayerRecords: true

##########################################
#                                        #
#              Translations              #
##########################################
# Enable or disable translations here.
#(Note: You must still have the files for that translation or it won't work.)
KJV: true

##########################################
#                                        #
#              BookChecks                #
##########################################
# How many chapters are made before notifying you.
# Set to 0 to never be notified.
BookConfigChapterNotifications: 5

# The settings below are how to check the bookconfig.yml file for the given translation.
# Create will overwrite books even if they already exist.
# Correct will overwrite incorrect parts of books and ignore others.
# Check will simply check if each book exists and create them if they don't.
# Ignore will do nothing.
KJVBookCheck: check
