# This is for messages that apply to all translations.
first: You must not put a space after the 1, and you must use 1, not first.
second: You must not put a space after the 2, and you must use 2, not second.
third: You must not put a space after the 3, and you must use 3, not third.
